import { calculateLongitudinalModes } from "../physics/longitudinal-modes.js";

function args(a) { return { speedMps: a.speedMps, densityKgM3: a.densityKgM3, wingAreaM2: a.wingAreaM2, meanChordM: a.meanChordM, pitchInertiaKgM2: a.pitchInertiaKgM2, cmAlphaPerRad: a.cmAlphaPerRad, cmQPerRad: a.cmQPerRad }; }
const requireStage4 = (capabilities) => { if (!capabilities?.["stability.pitch.cm-alpha"]) throw new TypeError("Stage 4 trim-response capability is required."); };
export const feature = {
  contractVersion: 4, id: "longitudinal-modes", title: "Reduced-order longitudinal modes", description: "Estimates short-period frequency and damping from the supplied linear pitch stiffness and damping derivatives.", category: "Stability · Student feature", learningMode: "aircraft", topicId: "stability", inputKeys: ["speedMps", "angleOfAttackDeg", "pitchRateRadS", "simulationDurationS"], requiresCapabilities: [{ id: "stability.pitch.cm-alpha", version: 1 }, { id: "dynamics.longitudinal.pitch", version: 1 }], providesCapabilities: [{ id: "dynamics.longitudinal.modes", version: 1 }], assumptions: ["The short-period mode is represented by one uncoupled linear pitch oscillator about the modeled condition."], validityLimits: ["This stage does not derive a phugoid: the available inputs do not define the required translational force derivatives."], simulation: { display: "analysis-only", durationS: 12, initialState: {}, controls: {}, disturbance: {} },
  analyze(aircraft, capabilities) { requireStage4(capabilities); const r = calculateLongitudinalModes(args(aircraft)); const duration = aircraft.simulationDurationS; const initial = aircraft.angleOfAttackDeg; const points = Array.from({ length: 61 }, (_, i) => { const t = duration * i / 60; const wn = r.shortPeriodNaturalFrequencyRadS; const z = r.shortPeriodDampingRatio; const wd = wn * Math.sqrt(Math.max(0, 1 - z ** 2)); return { x: t, y: r.shortPeriodStable ? initial * Math.exp(-z * wn * t) * Math.cos(wd * t) : initial * Math.cosh(wn * t) }; }); return { results: [{ label: "Short-period natural frequency", value: r.shortPeriodNaturalFrequencyRadS, unit: "rad/s", precision: 3 }, { label: "Short-period damping ratio", value: r.shortPeriodDampingRatio, unit: "", precision: 3, emphasis: true }, { label: "Short-period classification", value: r.shortPeriodStable ? "stable" : "not stable", unit: "" }, { label: "Phugoid", value: "not determined from supplied inputs", unit: "" }], verificationCases: [{ label: "Negative Cm-alpha gives positive modeled pitch stiffness", passed: calculateLongitudinalModes({ ...args(aircraft), cmAlphaPerRad: -0.8 }).pitchStiffnessNmPerRad > 0 }, { label: "Negative Cm-q gives positive damping coefficient", passed: calculateLongitudinalModes({ ...args(aircraft), cmQPerRad: -6 }).pitchDampingNmsPerRad > 0 }], decision: { question: "What short-period behavior follows from the reduced-order pitch model?", interpretation: `The short-period estimate has ωn=${r.shortPeriodNaturalFrequencyRadS.toFixed(3)} rad/s and ζ=${r.shortPeriodDampingRatio.toFixed(3)}. A phugoid conclusion is withheld.`, status: r.shortPeriodStable ? "pass" : "caution" }, plots: [{ id: "short-period-history", title: "Reduced-order short-period response", xLabel: "Time (s)", yLabel: "Angle perturbation (deg)", series: [{ label: "Pitch/angle perturbation", points }], regions: [], referenceLines: [{ axis: "y", value: 0, label: "Mode equilibrium" }] }], scene: null }; },
};
export const model = { kind: "derived", evaluate: ({ aircraft }) => ({ values: calculateLongitudinalModes(args(aircraft)) }) };
