import { calculatePitchDynamicResponse } from "../physics/pitch-dynamic-response.js";

function appliedMoment(capabilities) { const value = capabilities?.["loads.pitch.component-sum"]?.values?.netPitchMomentNm ?? capabilities?.["loads.pitch.component-sum"]?.momentsBodyNm?.y; if (!Number.isFinite(value)) throw new TypeError("Component-sum capability did not provide a finite pitch moment."); return value; }
const requireStage4 = (capabilities) => { if (!capabilities?.["stability.pitch.cm-alpha"]) throw new TypeError("Stage 4 trim-response capability is required."); };
function inputs(aircraft, appliedPitchMomentNm, pitchRateRadS = aircraft.pitchRateRadS) { return { pitchInertiaKgM2: aircraft.pitchInertiaKgM2, cmQPerRad: aircraft.cmQPerRad, pitchRateRadS, speedMps: aircraft.speedMps, densityKgM3: aircraft.densityKgM3, wingAreaM2: aircraft.wingAreaM2, meanChordM: aircraft.meanChordM, appliedPitchMomentNm }; }
export const feature = {
  contractVersion: 4, id: "pitch-dynamic-response", title: "Pitch dynamic response", description: "Combines applied pitch moment, pitch-rate damping, and pitch inertia for an instantaneous response model.", category: "Stability · Student feature", learningMode: "aircraft", topicId: "stability", inputKeys: ["pitchInertiaKgM2", "cmQPerRad", "pitchRateRadS", "simulationDurationS"], requiresCapabilities: [{ id: "stability.pitch.cm-alpha", version: 1 }, { id: "loads.pitch.component-sum", version: 1 }], providesCapabilities: [{ id: "dynamics.longitudinal.pitch", version: 1 }], assumptions: ["The pitch damping derivative uses q-hat = q c-bar/(2V) in the linear body-axis moment model."], validityLimits: ["The reduced-order rigid-body response omits translational coupling, nonlinear aerodynamics, actuator dynamics, and stall."], simulation: { display: "response", durationS: 12, initialState: { pitchRad: 0, pitchRateRadS: 0 }, controls: {}, disturbance: {}, plotStateKeys: ["pitchRad", "pitchRateRadS"] },
  analyze(aircraft, capabilities) { requireStage4(capabilities); const r = calculatePitchDynamicResponse(inputs(aircraft, appliedMoment(capabilities))); return { results: [{ label: "Applied pitch moment", value: appliedMoment(capabilities), unit: "N·m", precision: 3 }, { label: "Pitch damping moment", value: r.dampingPitchMomentNm, unit: "N·m", precision: 3 }, { label: "Pitch angular acceleration", value: r.pitchAngularAccelerationRadS2, unit: "rad/s²", precision: 3, emphasis: true }], verificationCases: [{ label: "Zero pitch rate produces zero damping moment", passed: Object.is(calculatePitchDynamicResponse(inputs(aircraft, 0, 0)).dampingPitchMomentNm, 0) }, { label: "Negative Cmq opposes positive pitch rate", passed: calculatePitchDynamicResponse(inputs({ ...aircraft, cmQPerRad: -6 }, 0, 0.2)).dampingPitchMomentNm < 0 }], decision: { question: "How do applied moment, pitch damping, and inertia set the pitch response?", interpretation: `The instantaneous net moment is ${r.netPitchMomentNm.toFixed(3)} N·m and produces ${r.pitchAngularAccelerationRadS2.toFixed(3)} rad/s².`, status: "neutral" }, plots: [], scene: null }; },
};
export const model = { kind: "state-model", evaluate: ({ aircraft, capabilities, state, momentsBodyNm }) => { const appliedPitchMomentNm = Number.isFinite(momentsBodyNm?.y) ? momentsBodyNm.y : appliedMoment(capabilities); const r = calculatePitchDynamicResponse(inputs(aircraft, appliedPitchMomentNm, state.pitchRateRadS ?? 0)); return { derivatives: { pitchRad: state.pitchRateRadS ?? 0, pitchRateRadS: r.pitchAngularAccelerationRadS2 }, values: r }; } };
