import { evaluateStabilityTradeStudy } from "../physics/stability-trade-study.js";

function args(a, cgM = a.cgM) { return { cgM, neutralPointM: a.neutralPointM, meanChordM: a.meanChordM, tailAreaM2: a.tailAreaM2, tailArmM: a.tailArmM, wingAreaM2: a.wingAreaM2, elevatorEffectiveness: a.elevatorEffectiveness, minimumStaticMargin: a.minimumStaticMargin }; }
const requireStage4 = (capabilities) => { if (!capabilities?.["stability.pitch.cm-alpha"]) throw new TypeError("Stage 4 trim-response capability is required."); };
export const feature = {
  contractVersion: 4, id: "stability-trade-study", title: "Stability and control trade study", description: "Compares static-margin requirement and normalized tail/elevator authority across CG position.", category: "Stability · Student feature", learningMode: "design", topicId: "stability", inputKeys: ["cgM", "tailAreaM2", "tailArmM", "elevatorEffectiveness", "minimumStaticMargin"], requiresCapabilities: [{ id: "stability.pitch.cm-alpha", version: 1 }, { id: "dynamics.longitudinal.modes", version: 1 }, { id: "dynamics.lateral.modes", version: 1 }], providesCapabilities: [{ id: "design.stability-control.trade", version: 1 }], assumptions: ["Static margin and the normalized tail/elevator authority index are screening metrics, not handling-quality ratings."], validityLimits: ["No acceptable control-authority threshold is inferred because none is supplied; only the stated minimum static margin is tested."], simulation: { display: "analysis-only", durationS: 1, initialState: {}, controls: {}, disturbance: {} },
  analyze(aircraft, capabilities) { requireStage4(capabilities); const r = evaluateStabilityTradeStudy(args(aircraft)); const cgs = Array.from({ length: 21 }, (_, i) => aircraft.neutralPointM - aircraft.meanChordM * (0.2 - i * 0.02)); return { results: [{ label: "Static margin", value: r.staticMarginPercent, unit: "% MAC", precision: 2 }, { label: "Minimum static margin", value: 100 * aircraft.minimumStaticMargin, unit: "% MAC", precision: 2 }, { label: "Static-margin requirement", value: r.staticMarginRequirementMet ? "met" : "not met", unit: "", emphasis: true }, { label: "Tail volume coefficient", value: r.tailVolumeCoefficient, unit: "", precision: 3 }, { label: "Control authority index", value: r.controlAuthorityIndex, unit: "", precision: 3 }], verificationCases: [{ label: "CG at the neutral point fails a positive minimum margin", passed: !evaluateStabilityTradeStudy(args({ ...aircraft, cgM: aircraft.neutralPointM })).staticMarginRequirementMet }, { label: "Increasing elevator effectiveness increases authority index", passed: evaluateStabilityTradeStudy(args({ ...aircraft, elevatorEffectiveness: 0.9 })).controlAuthorityIndex > evaluateStabilityTradeStudy(args({ ...aircraft, elevatorEffectiveness: 0.3 })).controlAuthorityIndex }], decision: { question: "Does this configuration meet the stated static-margin requirement while retaining modeled control leverage?", interpretation: `The static-margin requirement is ${r.staticMarginRequirementMet ? "met" : "not met"}; the authority index is ${r.controlAuthorityIndex.toFixed(3)}, for which no acceptance threshold was supplied.`, status: r.staticMarginRequirementMet ? "pass" : "caution" }, plots: [{ id: "trade-static-margin", title: "CG trade against static-margin requirement", xLabel: "CG x-location (m)", yLabel: "Static margin", series: [{ label: "Static margin", points: cgs.map((cgM) => ({ x: cgM, y: evaluateStabilityTradeStudy(args(aircraft, cgM)).staticMargin })) }], regions: [], referenceLines: [{ axis: "y", value: aircraft.minimumStaticMargin, label: "Minimum static margin" }, { axis: "x", value: aircraft.neutralPointM, label: "Neutral point" }] }], scene: null }; },
};
export const model = { kind: "derived", evaluate: ({ aircraft }) => ({ values: evaluateStabilityTradeStudy(args(aircraft)) }) };
