import { calculateStickFreeEffect } from "../physics/stick-free-effect.js";

function fixedDerivative(capabilities) { const value = capabilities?.["control.pitch.tail-elevator"]?.values?.elevatorControlDerivativePerRad; if (!Number.isFinite(value)) throw new TypeError("Tail/elevator capability did not provide a finite control derivative."); return value; }
const requireStage4 = (capabilities) => { if (!capabilities?.["stability.pitch.cm-alpha"]) throw new TypeError("Stage 4 trim-response capability is required."); };
export const feature = {
  contractVersion: 4, id: "stick-free-effect", title: "Stick-free elevator effectiveness", description: "Shows how elevator float reduces the available fixed-control pitch authority.", category: "Stability · Student feature", learningMode: "aircraft", topicId: "stability", inputKeys: ["elevatorEffectiveness", "stickFreeFactor"], requiresCapabilities: [{ id: "stability.pitch.cm-alpha", version: 1 }, { id: "control.pitch.tail-elevator", version: 1 }], providesCapabilities: [{ id: "control.pitch.stick-free", version: 1 }], assumptions: ["A supplied scalar stick-free factor represents the reduction from fixed to free elevator authority."], validityLimits: ["The model does not calculate hinge moments, freeplay, control-system friction, or pilot force."], simulation: { display: "analysis-only", durationS: 1, initialState: {}, controls: {}, disturbance: {} },
  analyze(aircraft, capabilities) { requireStage4(capabilities); const r = calculateStickFreeEffect({ ...aircraft, fixedControlDerivativePerRad: fixedDerivative(capabilities) }); return { results: [{ label: "Effective elevator effectiveness", value: r.effectiveElevatorEffectiveness, unit: "", precision: 3 }, { label: "Stick-free control derivative", value: r.stickFreeControlDerivativePerRad, unit: "1/rad", precision: 3, emphasis: true }, { label: "Authority retained", value: r.authorityRetainedPercent, unit: "%", precision: 1 }], verificationCases: [{ label: "A factor of one preserves all authority", passed: calculateStickFreeEffect({ fixedControlDerivativePerRad: -0.2, elevatorEffectiveness: 0.7, stickFreeFactor: 1 }).authorityLostPercent === 0 }, { label: "A factor of zero removes the modeled authority", passed: Object.is(calculateStickFreeEffect({ fixedControlDerivativePerRad: -0.2, elevatorEffectiveness: 0.7, stickFreeFactor: 0 }).stickFreeControlDerivativePerRad, 0) }], decision: { question: "How much pitch-control authority remains with the elevator free?", interpretation: `${r.authorityRetainedPercent.toFixed(1)}% of the normalized fixed-control authority remains.`, status: "neutral" }, plots: [], scene: null }; },
};
export const model = { kind: "derived", evaluate: ({ aircraft, capabilities }) => ({ values: calculateStickFreeEffect({ ...aircraft, fixedControlDerivativePerRad: fixedDerivative(capabilities) }) }) };
