import { calculateTailElevatorContribution } from "../physics/tail-elevator-contribution.js";

const reference = { tailAreaM2: 0.09, tailArmM: 0.55, wingAreaM2: 0.5, meanChordM: 0.32, elevatorDeflectionDeg: 10, elevatorEffectiveness: 0.7 };
const requireStage4 = (capabilities) => { if (!capabilities?.["stability.pitch.cm-alpha"]) throw new TypeError("Stage 4 trim-response capability is required."); };
export const feature = {
  contractVersion: 4, id: "tail-elevator-contribution", title: "Tail and elevator contribution", description: "Uses tail volume and elevator effectiveness to form a nondimensional pitch-control contribution.", category: "Stability · Student feature", learningMode: "aircraft", topicId: "stability",
  inputKeys: Object.keys(reference), requiresCapabilities: [{ id: "stability.pitch.cm-alpha", version: 1 }, { id: "stability.longitudinal.static-margin", version: 1 }], providesCapabilities: [{ id: "control.pitch.tail-elevator", version: 1 }],
  assumptions: ["The normalized teaching relation is Cm_delta_e = -V_H times elevator effectiveness; omitted tail efficiency and lift-curve factors are unity."], validityLimits: ["This nondimensional leverage model is not a hinge-moment, control-force, stall, or certification model."], simulation: { display: "analysis-only", durationS: 1, initialState: {}, controls: {}, disturbance: {} },
  analyze(aircraft, capabilities) { requireStage4(capabilities); const r = calculateTailElevatorContribution(aircraft); const ref = calculateTailElevatorContribution(reference); const deflections = [-15, -10, -5, 0, 5, 10, 15]; return { results: [{ label: "Tail volume coefficient", value: r.tailVolumeCoefficient, unit: "", precision: 3 }, { label: "Elevator control derivative", value: r.elevatorControlDerivativePerRad, unit: "1/rad", precision: 3 }, { label: "Elevator moment-coefficient change", value: r.elevatorMomentCoefficientChange, unit: "", precision: 4, emphasis: true }], verificationCases: [{ label: "Reference tail volume is 0.3094", passed: Math.abs(ref.tailVolumeCoefficient - 0.309375) < 1e-12 }, { label: "Zero deflection gives zero contribution", passed: Object.is(calculateTailElevatorContribution({ ...reference, elevatorDeflectionDeg: 0 }).elevatorMomentCoefficientChange, 0) }], decision: { question: "How much normalized pitch-control leverage does the tail/elevator provide?", interpretation: `The modeled tail volume is ${r.tailVolumeCoefficient.toFixed(3)} and the selected deflection changes Cm by ${r.elevatorMomentCoefficientChange.toFixed(4)}.`, status: "neutral" }, plots: [{ id: "elevator-cm", title: "Elevator contribution", xLabel: "Elevator deflection (deg)", yLabel: "ΔCm", series: [{ label: "Tail/elevator", points: deflections.map((elevatorDeflectionDeg) => ({ x: elevatorDeflectionDeg, y: calculateTailElevatorContribution({ ...aircraft, elevatorDeflectionDeg }).elevatorMomentCoefficientChange })) }], regions: [], referenceLines: [{ axis: "x", value: 0, label: "Neutral elevator" }, { axis: "y", value: 0, label: "Zero contribution" }] }], scene: null }; },
};
export const model = { kind: "derived", evaluate: ({ aircraft }) => ({ values: calculateTailElevatorContribution(aircraft) }) };
